name: Example Workflow

on: [push]  # Triggers the workflow on every push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1002241@ds.study.iitm.ac.in
        run: echo "Hello, world!"
